package ai.moying.iview.production.jdbc
import ai.moying.iview.production.*
import com.fasterxml.jackson.core.type.TypeReference
import com.fasterxml.jackson.databind.ObjectMapper
import org.springframework.jdbc.core.RowMapper
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate
import org.springframework.jdbc.core.simple.SimpleJdbcInsert
import org.springframework.stereotype.Repository
import java.time.Instant
@Repository class JdbcProductionRepository(private val jdbc:NamedParameterJdbcTemplate,private val json:ObjectMapper):ProductionRepository {
 private val ri by lazy{ins("iview_production_rule","template_id","quantity_point_id","qualified_point_id","enabled","rule_version")}; private val pi by lazy{ins("iview_production_record","device_id","quantity","qualified_quantity","start_time","end_time","rule_version","attrs_json")}
 override fun listRules()=jdbc.query("SELECT * FROM iview_production_rule ORDER BY id", emptyMap<String,Any>(),rm); override fun findRule(id:Long)=one("SELECT * FROM iview_production_rule WHERE id=:id",mapOf("id" to id),rm)
 override fun createRule(c:ProductionRuleCommand):ProductionRule {val id=ri.executeAndReturnKey(vals(c,1)).toLong();return requireNotNull(findRule(id))}; override fun updateRule(id:Long,c:ProductionRuleCommand):ProductionRule? {val n=jdbc.update("UPDATE iview_production_rule SET template_id=:template_id,quantity_point_id=:quantity_point_id,qualified_point_id=:qualified_point_id,enabled=:enabled,rule_version=rule_version+1,updated_at=CURRENT_TIMESTAMP WHERE id=:id",vals(c,0)+("id" to id));return if(n==0)null else findRule(id)}; override fun deleteRule(id:Long)=jdbc.update("DELETE FROM iview_production_rule WHERE id=:id",mapOf("id" to id))>0
 override fun checkpoint(d:Long,p:Long)=one("SELECT * FROM iview_production_checkpoint WHERE device_id=:d AND point_id=:p",mapOf("d" to d,"p" to p),cm); override fun saveCheckpoint(c:ProductionCheckpoint){ if(checkpoint(c.deviceId,c.pointId)==null) jdbc.update("INSERT INTO iview_production_checkpoint(device_id,point_id,quantity,observed_at) VALUES(:d,:p,:q,:t)",mapOf("d" to c.deviceId,"p" to c.pointId,"q" to c.quantity,"t" to c.observedAt)) else jdbc.update("UPDATE iview_production_checkpoint SET quantity=:q,observed_at=:t,updated_at=CURRENT_TIMESTAMP WHERE device_id=:d AND point_id=:p",mapOf("d" to c.deviceId,"p" to c.pointId,"q" to c.quantity,"t" to c.observedAt)) }
 override fun findRecord(d:Long,s:Instant,e:Instant)=one("SELECT * FROM iview_production_record WHERE device_id=:d AND start_time=:s AND end_time=:e",mapOf("d" to d,"s" to s,"e" to e),prm); override fun createRecord(d:Long,q:Long,g:Long,s:Instant,e:Instant,v:String,a:Map<String,String>):ProductionRecord {val id=pi.executeAndReturnKey(mapOf("device_id" to d,"quantity" to q,"qualified_quantity" to g,"start_time" to s,"end_time" to e,"rule_version" to v,"attrs_json" to json.writeValueAsString(a))).toLong();return requireNotNull(one("SELECT * FROM iview_production_record WHERE id=:id",mapOf("id" to id),prm))}
 override fun recordsInWindow(deviceId:Long,start:Instant,endExclusive:Instant)=jdbc.query("SELECT * FROM iview_production_record WHERE device_id=:d AND end_time>:s AND start_time<:e ORDER BY start_time",mapOf("d" to deviceId,"s" to start,"e" to endExclusive),prm)
 override fun listRecords(f:ProductionFilter):ProductionPage<ProductionRecord>{val p=mutableMapOf<String,Any>("l" to f.pageSize,"o" to (f.page-1)*f.pageSize);val w=f.deviceId?.let{p["d"]=it;"WHERE device_id=:d"}?:"";return ProductionPage(jdbc.query("SELECT * FROM iview_production_record $w ORDER BY id DESC LIMIT :l OFFSET :o",p,prm),jdbc.queryForObject("SELECT COUNT(*) FROM iview_production_record $w",p,Long::class.java)?:0,f.page,f.pageSize)}; override fun deleteBefore(c:Instant)=jdbc.update("DELETE FROM iview_production_record WHERE end_time<:c",mapOf("c" to c))
 private fun vals(c:ProductionRuleCommand,v:Int)=mapOf("template_id" to c.templateId,"quantity_point_id" to c.quantityPointId,"qualified_point_id" to c.qualifiedPointId,"enabled" to c.enabled,"rule_version" to v); private fun ins(t:String,vararg c:String)=SimpleJdbcInsert(jdbc.jdbcTemplate).withTableName(t).usingGeneratedKeyColumns("id").usingColumns(*c); private fun <T>one(s:String,p:Map<String,Any?>,m:RowMapper<T>)=jdbc.query(s,p,m).firstOrNull();private fun ti(rs:java.sql.ResultSet,n:String)=rs.getTimestamp(n).toInstant()
 private val rm=RowMapper{r,_->ProductionRule(r.getLong("id"),r.getLong("template_id"),r.getLong("quantity_point_id"),(r.getObject("qualified_point_id")as?Number)?.toLong(),r.getBoolean("enabled"),r.getLong("rule_version"),ti(r,"created_at"),ti(r,"updated_at"))};private val cm=RowMapper{r,_ ->ProductionCheckpoint(r.getLong("device_id"),r.getLong("point_id"),r.getLong("quantity"),ti(r,"observed_at"))};private val prm=RowMapper{r,_ ->ProductionRecord(r.getLong("id"),r.getLong("device_id"),r.getLong("quantity"),r.getLong("qualified_quantity"),ti(r,"start_time"),ti(r,"end_time"),r.getString("rule_version"),json.readValue(r.getString("attrs_json"),object:TypeReference<Map<String,String>>(){}),ti(r,"created_at"))}
}
