CREATE TABLE iview_data_model (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_id BIGINT NOT NULL,
    model_name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(500) NOT NULL DEFAULT '',
    model_status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    latest_schema_version INT NOT NULL DEFAULT 0,
    published_schema_version INT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_iview_data_model_dataset FOREIGN KEY (dataset_id) REFERENCES iview_dataset(id) ON DELETE RESTRICT
);

CREATE TABLE iview_data_model_schema (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id BIGINT NOT NULL,
    schema_version INT NOT NULL,
    fields_json CLOB NOT NULL,
    fingerprint VARCHAR(4000) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_iview_data_model_schema_model FOREIGN KEY (model_id) REFERENCES iview_data_model(id) ON DELETE CASCADE,
    CONSTRAINT uq_iview_data_model_schema_version UNIQUE (model_id, schema_version)
);
