CREATE TABLE iview_department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_code VARCHAR(64) NOT NULL UNIQUE,
    department_name VARCHAR(100) NOT NULL,
    parent_id BIGINT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (parent_id) REFERENCES iview_department(id)
);

CREATE INDEX idx_iview_department_parent ON iview_department(parent_id, sort_order);

CREATE TABLE iview_user_department (
    user_id BIGINT PRIMARY KEY,
    department_id BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES iview_user(id) ON DELETE CASCADE,
    FOREIGN KEY (department_id) REFERENCES iview_department(id) ON DELETE RESTRICT
);

CREATE INDEX idx_iview_user_department_department ON iview_user_department(department_id);
