CREATE TABLE iview_device_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_code VARCHAR(50) NOT NULL UNIQUE,
    group_name VARCHAR(100) NOT NULL,
    description VARCHAR(500) NOT NULL DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE iview_device_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_code VARCHAR(32) NOT NULL UNIQUE,
    template_name VARCHAR(100) NOT NULL,
    protocol_type VARCHAR(50) NOT NULL,
    protocol_config TEXT NOT NULL DEFAULT '{}',
    collect_interval_ms INTEGER NOT NULL DEFAULT 1000,
    timeout_ms INTEGER NOT NULL DEFAULT 5000,
    description VARCHAR(500) NOT NULL DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_template_collect_interval CHECK (collect_interval_ms >= 10),
    CONSTRAINT chk_template_timeout CHECK (timeout_ms >= 100)
);

CREATE TABLE iview_template_point (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id BIGINT NOT NULL REFERENCES iview_device_template(id) ON DELETE CASCADE,
    point_name VARCHAR(100) NOT NULL,
    point_code VARCHAR(50) NOT NULL,
    data_type VARCHAR(30) NOT NULL,
    address VARCHAR(100) NOT NULL DEFAULT '',
    unit VARCHAR(20) NOT NULL DEFAULT '',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    value_enum TEXT NOT NULL DEFAULT '[]',
    point_config TEXT NOT NULL DEFAULT '{}',
    description VARCHAR(200) NOT NULL DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_template_point_code UNIQUE (template_id, point_code)
);

CREATE TABLE iview_device (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_sn VARCHAR(32) NOT NULL UNIQUE,
    device_name VARCHAR(100) NOT NULL,
    template_id BIGINT NOT NULL REFERENCES iview_device_template(id),
    group_id BIGINT REFERENCES iview_device_group(id),
    line_id VARCHAR(100),
    device_vendor VARCHAR(100),
    device_type VARCHAR(100),
    config_json TEXT NOT NULL DEFAULT '{}',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    description VARCHAR(500) NOT NULL DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_iview_device_template ON iview_device(template_id);
CREATE INDEX idx_iview_device_group ON iview_device(group_id);
CREATE INDEX idx_iview_point_template ON iview_template_point(template_id);
