CREATE TABLE iview_point_sample (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL REFERENCES iview_device(id) ON DELETE CASCADE,
    point_id BIGINT NOT NULL REFERENCES iview_template_point(id) ON DELETE CASCADE,
    observed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    received_at TIMESTAMP WITH TIME ZONE NOT NULL,
    value_json TEXT,
    quality VARCHAR(40) NOT NULL,
    source VARCHAR(50) NOT NULL,
    diagnostic VARCHAR(1000)
);

CREATE INDEX idx_iview_sample_device_time ON iview_point_sample(device_id, observed_at DESC);
CREATE INDEX idx_iview_sample_point_time ON iview_point_sample(point_id, observed_at DESC);
