CREATE TABLE iview_template_control_point (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id BIGINT NOT NULL REFERENCES iview_device_template(id) ON DELETE CASCADE,
    point_name VARCHAR(100) NOT NULL,
    point_code VARCHAR(50) NOT NULL,
    data_type VARCHAR(30) NOT NULL DEFAULT 'int16',
    address VARCHAR(100) NOT NULL DEFAULT '',
    default_value VARCHAR(100) NOT NULL DEFAULT '',
    value_range VARCHAR(200) NOT NULL DEFAULT '',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    value_enum TEXT NOT NULL DEFAULT '[]',
    point_config TEXT NOT NULL DEFAULT '{}',
    description VARCHAR(200) NOT NULL DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_template_control_point_code UNIQUE (template_id, point_code)
);

CREATE TABLE iview_control_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL,
    device_name VARCHAR(100) NOT NULL DEFAULT '',
    control_point_id BIGINT NOT NULL,
    point_name VARCHAR(100) NOT NULL DEFAULT '',
    control_value TEXT NOT NULL DEFAULT '',
    status INTEGER NOT NULL,
    message VARCHAR(500) NOT NULL DEFAULT '',
    operator_id BIGINT NOT NULL DEFAULT 0,
    operator_name VARCHAR(100) NOT NULL DEFAULT 'system',
    source VARCHAR(20) NOT NULL DEFAULT 'web',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_control_log_status CHECK (status IN (0, 1))
);

CREATE INDEX idx_iview_control_point_template ON iview_template_control_point(template_id);
CREATE INDEX idx_iview_control_log_device ON iview_control_log(device_id, created_at);
CREATE INDEX idx_iview_control_log_point ON iview_control_log(control_point_id, created_at);
