CREATE TABLE iview_push_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_name VARCHAR(100) NOT NULL,
    push_type VARCHAR(20) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    priority INTEGER NOT NULL DEFAULT 0,
    timeout_ms INTEGER NOT NULL DEFAULT 5000,
    retry_count INTEGER NOT NULL DEFAULT 3,
    retry_delay_ms INTEGER NOT NULL DEFAULT 1000,
    settings_json TEXT NOT NULL DEFAULT '{}',
    description VARCHAR(500) NOT NULL DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_push_type CHECK (push_type IN ('http', 'mqtt')),
    CONSTRAINT chk_push_timeout CHECK (timeout_ms BETWEEN 100 AND 300000),
    CONSTRAINT chk_push_retry_count CHECK (retry_count BETWEEN 0 AND 20),
    CONSTRAINT chk_push_retry_delay CHECK (retry_delay_ms BETWEEN 0 AND 300000)
);

CREATE TABLE iview_push_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_id BIGINT NOT NULL,
    config_name VARCHAR(100) NOT NULL,
    device_sn VARCHAR(50) NOT NULL,
    status INTEGER NOT NULL,
    retry_count INTEGER NOT NULL DEFAULT 0,
    message VARCHAR(500) NOT NULL DEFAULT '',
    payload_size INTEGER NOT NULL DEFAULT 0,
    duration_ms BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_push_log_status CHECK (status IN (0, 1, 2))
);

CREATE INDEX idx_iview_push_config_enabled ON iview_push_config(enabled, priority);
CREATE INDEX idx_iview_push_log_config ON iview_push_log(config_id, created_at);
CREATE INDEX idx_iview_push_log_device ON iview_push_log(device_sn, created_at);
