CREATE TABLE iview_alarm_classification_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pattern VARCHAR(500) NOT NULL,
    category INTEGER NOT NULL,
    priority INTEGER NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_alarm_category CHECK (category >= 0),
    CONSTRAINT chk_alarm_priority CHECK (priority >= 0)
);

CREATE TABLE iview_device_alarm (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL,
    abnormal_at TIMESTAMP WITH TIME ZONE NOT NULL,
    recovered_at TIMESTAMP WITH TIME ZONE,
    alarm_content VARCHAR(500),
    alarm_category INTEGER,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_device_alarm_status CHECK (status IN ('ACTIVE', 'RECOVERED')),
    CONSTRAINT chk_recovered_alarm CHECK ((status = 'ACTIVE' AND recovered_at IS NULL) OR (status = 'RECOVERED' AND recovered_at IS NOT NULL))
);

CREATE INDEX idx_iview_alarm_rule_order ON iview_alarm_classification_rule(enabled, priority, id);
CREATE INDEX idx_iview_device_alarm_active ON iview_device_alarm(device_id, status, id);
CREATE INDEX idx_iview_device_alarm_history ON iview_device_alarm(abnormal_at, status);
