CREATE TABLE iview_machine_state_rule (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, template_id BIGINT NOT NULL, point_id BIGINT NOT NULL,
 standard_mapping_json TEXT NOT NULL, runtime_mapping_json TEXT NOT NULL, default_status VARCHAR(32) NOT NULL,
 default_runtime_state VARCHAR(32) NOT NULL, enabled BOOLEAN NOT NULL DEFAULT TRUE, rule_version BIGINT NOT NULL DEFAULT 1,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE iview_device_current_state (
 device_id BIGINT PRIMARY KEY, raw_status VARCHAR(64), standard_status VARCHAR(32) NOT NULL, runtime_state VARCHAR(32) NOT NULL,
 source VARCHAR(50) NOT NULL, rule_version VARCHAR(100) NOT NULL, reported_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE iview_machine_state_interval (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, device_id BIGINT NOT NULL, state VARCHAR(32) NOT NULL,
 started_at TIMESTAMP WITH TIME ZONE NOT NULL, ended_at TIMESTAMP WITH TIME ZONE, rule_version VARCHAR(100) NOT NULL
);
CREATE INDEX idx_iview_state_interval_device_time ON iview_machine_state_interval(device_id, started_at);
