plugins {
    kotlin("jvm")
    kotlin("plugin.spring")
    id("org.springframework.boot")
    id("io.spring.dependency-management")
}

kotlin { jvmToolchain(21) }

dependencies {
    implementation(project(":modules:core-model"))
    implementation(project(":modules:protocol-spi"))
    implementation(project(":modules:protocol-modbus-tcp"))
    implementation(project(":modules:protocol-modbus-rtu"))
    implementation(project(":modules:protocol-mitsubishi-mc3e"))
    implementation(project(":modules:protocol-mitsubishi-mc4e"))
    implementation(project(":modules:protocol-mitsubishi-mca1e"))
    implementation(project(":modules:protocol-omron-fins"))
    implementation(project(":modules:protocol-omron-fins-udp"))
    implementation(project(":modules:protocol-s7"))
    implementation(project(":modules:protocol-opcua"))
    implementation(project(":modules:collector"))
    implementation(project(":modules:device"))
    implementation(project(":modules:device-jdbc"))
    implementation(project(":modules:oee"))
    implementation(project(":modules:machine-state"))
    implementation(project(":modules:machine-state-jdbc"))
    implementation(project(":modules:production"))
    implementation(project(":modules:production-jdbc"))
    implementation(project(":modules:production-plan"))
    implementation(project(":modules:production-plan-jdbc"))
    implementation(project(":modules:alarm"))
    implementation(project(":modules:alarm-jdbc"))
    implementation(project(":modules:outbound"))
    implementation(project(":modules:outbound-jdbc"))
    implementation(project(":modules:query-api"))
    implementation(project(":modules:query-api-jdbc"))
    implementation(project(":modules:telemetry"))
    implementation(project(":modules:telemetry-jdbc"))
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.springframework.boot:spring-boot-starter-jdbc")
    implementation("org.springframework.boot:spring-boot-flyway")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
    implementation("tools.jackson.module:jackson-module-kotlin")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310")
    implementation("org.jetbrains.kotlin:kotlin-reflect")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2")
    implementation("org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5")
    implementation("org.mongodb:mongodb-driver-sync")
    runtimeOnly("com.h2database:h2")
    runtimeOnly("org.postgresql:postgresql")
    runtimeOnly("org.flywaydb:flyway-database-postgresql")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("org.springframework.boot:spring-boot-webmvc-test")
    testImplementation(kotlin("test"))
}
