package ai.moying.iview.protocol.modbus.rtu

import ai.moying.iview.core.device.*
import ai.moying.iview.protocol.*
import com.fazecast.jSerialComm.SerialPort
import com.fazecast.jSerialComm.SerialPortTimeoutException
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.IOException
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.time.Duration
import java.time.Instant
import java.util.concurrent.locks.ReentrantLock
import kotlin.concurrent.withLock

class ModbusRtuDriver : ProtocolDriver {
    override val protocolType = "modbus_rtu"
    override fun validate(device: DeviceDefinition): ValidationResult { val p=device.connectionProperties; val issues=buildList { if ((p["serial_port"]?:p["serialPort"]).isNullOrBlank()) add(ValidationIssue("serial_port","串口不能为空")); if ((p["baud_rate"]?:p["baudRate"]?:"9600").toIntOrNull() !in setOf(1200,2400,4800,9600,19200,38400,57600,115200)) add(ValidationIssue("baud_rate","波特率不受支持")); if ((p["slave_id"]?:p["slaveId"]?:"1").toIntOrNull() !in 1..247) add(ValidationIssue("slave_id","从站 ID 必须在 1 到 247 之间")); if ((p["timeout"]?:"5000").toIntOrNull() !in 100..300000) add(ValidationIssue("timeout","超时必须在 100 到 300000 毫秒之间")) }; return ValidationResult(issues) }
    override suspend fun diagnose(device: DeviceDefinition): DiagnosticResult = withContext(Dispatchers.IO) { val valid=validate(device); if(!valid.valid)return@withContext DiagnosticResult(listOf(DiagnosticCheck("配置校验",false,Duration.ZERO,valid.issues.joinToString("；"){it.message}))); val c=RtuConfig.from(device); val found=SerialPort.getCommPorts().any{it.systemPortName==c.port}; DiagnosticResult(listOf(DiagnosticCheck("配置校验",true,Duration.ZERO,"配置有效"),DiagnosticCheck("串口枚举",found,Duration.ZERO,if(found)"已发现 ${c.port}" else "未发现 ${c.port}"))) }
    override suspend fun connect(device: DeviceDefinition): ProtocolSession = withContext(Dispatchers.IO) { val v=validate(device); require(v.valid){v.issues.joinToString("；"){it.message}}; RtuSession(device,RtuConfig.from(device)).also{it.open()} }
}
private data class RtuConfig(val port:String,val baud:Int,val dataBits:Int,val stopBits:Int,val parity:Int,val slave:Int,val timeout:Int){companion object{fun from(d:DeviceDefinition)=d.connectionProperties.let{p->RtuConfig((p["serial_port"]?:p["serialPort"]).orEmpty(),(p["baud_rate"]?:p["baudRate"]?:"9600").toInt(),(p["data_bits"]?:p["dataBits"]?:"8").toInt(),(p["stop_bits"]?:p["stopBits"]?:"1").toInt(),when((p["parity"]?:"N").uppercase()){"E"->SerialPort.EVEN_PARITY;"O"->SerialPort.ODD_PARITY;else->SerialPort.NO_PARITY},(p["slave_id"]?:p["slaveId"]?:"1").toInt(),(p["timeout"]?:"5000").toInt())}}}
private class RtuSession(private val device:DeviceDefinition,private val c:RtuConfig):ProtocolSession { private val client=RtuClient(c.slave){SerialRtuTransport(c)}; override val connected get()=client.connected; fun open()=client.open(); override fun close()=client.close()
 override suspend fun read(points:List<PointDefinition>):List<PointValue> = withContext(Dispatchers.IO){points.map{p->val start=Instant.now();runCatching{readPoint(p)}.fold({PointValue(device.id,p.id,start,Instant.now(),it,ValueQuality.GOOD,"modbus_rtu")},{e->PointValue(device.id,p.id,start,Instant.now(),null,if(e is SerialPortTimeoutException)ValueQuality.TIMEOUT else if(e is IllegalArgumentException||e is ModbusRtuException)ValueQuality.BAD_RESPONSE else ValueQuality.OFFLINE,"modbus_rtu",e.message)})}}
 override suspend fun write(writes:List<PointWrite>):List<WriteResult> = withContext(Dispatchers.IO){writes.map{w->if(w.point.access==PointAccess.READ_ONLY)WriteResult(false,"点位只读") else runCatching{writePoint(w.point,w.value)}.fold({WriteResult(true)},{WriteResult(false,it.message)})}}
 private fun readPoint(p:PointDefinition):Any?{val cfg=PointCfg.from(p);val count=if(cfg.bits)1 else width(p.dataType);val data=exchange(cfg.function,bytes(cfg.address,count));require(data.isNotEmpty()&&data[0].u()+1==data.size){"RTU 读取响应长度不匹配"};val raw=if(cfg.bits)data[1].u()and 1==1 else decode(data.copyOfRange(1,data.size),p.dataType,cfg.order);return cfg.scale(raw)}
 private fun writePoint(p:PointDefinition,v:Any?){val cfg=PointCfg.from(p);when(cfg.reg){"coil"->exchange(5,bytes(cfg.address,if(bool(v))0xff00 else 0));"holding"->{val data=encode(cfg.unscale(v),p.dataType,cfg.order);exchange(16,byteArrayOf((cfg.address ushr 8).toByte(),cfg.address.toByte(),0,(data.size/2).toByte(),data.size.toByte(),*data))};else->throw IllegalArgumentException("${cfg.reg} 不支持写入")}}
 private fun exchange(fn:Int,payload:ByteArray):ByteArray=client.exchange(fn,payload)
}

internal interface RtuTransport { val connected:Boolean; fun open(); fun close(); fun write(bytes:ByteArray); fun read(length:Int):ByteArray }
private class SerialRtuTransport(private val c:RtuConfig):RtuTransport { private var port:SerialPort?=null; override val connected get()=port?.isOpen==true; override fun open(){close();port=SerialPort.getCommPort(c.port).also{it.setComPortParameters(c.baud,c.dataBits,c.stopBits,c.parity);it.setComPortTimeouts(SerialPort.TIMEOUT_READ_BLOCKING,c.timeout,c.timeout);if(!it.openPort())throw IOException("无法打开串口 ${c.port}")}};override fun close(){runCatching{port?.closePort()};port=null};override fun write(bytes:ByteArray){val out=port?.outputStream?:throw IOException("串口未连接");out.write(bytes);out.flush()};override fun read(length:Int):ByteArray{val input=port?.inputStream?:throw IOException("串口未连接");return ByteArray(length).also{readFully(input,it)}} }
internal class RtuClient(private val slave:Int,private val factory:()->RtuTransport){private val lock=ReentrantLock();private var transport:RtuTransport?=null;val connected get()=lock.withLock{transport?.connected==true};fun open()=lock.withLock{transport?.close();transport=factory().also{it.open()}};fun close()=lock.withLock{transport?.close();transport=null};fun exchange(fn:Int,payload:ByteArray):ByteArray=lock.withLock{try{frame(fn,payload)}catch(first:IOException){transport?.close();transport=factory().also{it.open()};frame(fn,payload)}};private fun frame(fn:Int,payload:ByteArray):ByteArray{val wire=transport?:throw IOException("串口未连接");wire.write(byteArrayOf(slave.toByte(),fn.toByte(),*payload).withCrc());val head=wire.read(3);require(head[0].u()==slave){"从站 ID 不匹配"};if(head[1].u()==(fn or 0x80)){val all=head+wire.read(2);verify(all);throw ModbusRtuException(head[2].u())};require(head[1].u()==fn){"功能码不匹配"};val body=wire.read(if(fn in 1..4)head[2].u()+2 else 5);verify(head+body);return if(fn in 1..4)head.copyOfRange(2,3)+body.copyOfRange(0,body.size-2)else byteArrayOf(head[2])+body.copyOfRange(0,3)}}
private class ModbusRtuException(code:Int):RuntimeException("Modbus 异常响应: $code")
private data class PointCfg(val reg:String,val address:Int,val order:String,val factor:Double,val offset:Double){val bits get()=reg=="coil"||reg=="discrete";val function get()=when(reg){"coil"->1;"discrete"->2;"input"->4;else->3};fun scale(v:Any?)=if(factor==1.0&&offset==0.0)v else num(v)*factor+offset;fun unscale(v:Any?)=if(factor==1.0&&offset==0.0)v else (num(v)-offset)/factor;companion object{fun from(p:PointDefinition):PointCfg{val x=p.properties;val reg=(x["register_type"]?:x["registerType"]?:"holding").lowercase();require(reg in setOf("coil","discrete","input","holding"));val a=p.address.toInt()-when{p.address.toInt()>=40001->40001;p.address.toInt()>=30001->30001;p.address.toInt()>=10001->10001;else->0};return PointCfg(reg,a,(x["byte_order"]?:x["byteOrder"]?:"big").lowercase(),(x["value_scale"]?:"1").toDouble(),(x["value_offset"]?:"0").toDouble())}}}
private fun Byte.u()=toInt()and 255; private fun bytes(a:Int,b:Int)=byteArrayOf((a ushr 8).toByte(),a.toByte(),(b ushr 8).toByte(),b.toByte()); private fun width(t:PointDataType)=when(t){PointDataType.BOOLEAN,PointDataType.INT16,PointDataType.UINT16->1;PointDataType.INT32,PointDataType.UINT32,PointDataType.FLOAT32->2;PointDataType.INT64,PointDataType.UINT64,PointDataType.FLOAT64->4;else->error("不支持的数据类型")}; private fun num(v:Any?)=when(v){is Number->v.toDouble();is Boolean->if(v)1.0 else 0.0;is String->v.toDouble();else->error("不是数值")};private fun bool(v:Any?)=v is Boolean&&v||v is Number&&v.toDouble()!=0.0||v is String&&v in setOf("1","true","on")
private fun decode(b:ByteArray,t:PointDataType,o:String):Any{val x=order(b,o);val q=ByteBuffer.wrap(x).order(ByteOrder.BIG_ENDIAN);return when(t){PointDataType.BOOLEAN->q.short.toInt()!=0;PointDataType.INT16->q.short;PointDataType.UINT16->q.short.toInt()and 65535;PointDataType.INT32->q.int;PointDataType.UINT32->q.int.toLong()and 0xffffffffL;PointDataType.INT64,PointDataType.UINT64->q.long;PointDataType.FLOAT32->q.float;PointDataType.FLOAT64->q.double;else->error("不支持的数据类型")}}
private fun encode(v:Any?,t:PointDataType,o:String)=order(ByteBuffer.allocate(width(t)*2).order(ByteOrder.BIG_ENDIAN).apply{when(t){PointDataType.BOOLEAN->putShort(if(bool(v))1 else 0);PointDataType.INT16,PointDataType.UINT16->putShort(num(v).toInt().toShort());PointDataType.INT32,PointDataType.UINT32->putInt(num(v).toInt());PointDataType.INT64,PointDataType.UINT64->putLong(num(v).toLong());PointDataType.FLOAT32->putFloat(num(v).toFloat());PointDataType.FLOAT64->putDouble(num(v));else->error("不支持的数据类型")}}.array(),o)
private fun order(b:ByteArray,o:String)=when(o){"big"->b;"little"->b.reversedArray();"cdab"->if(b.size==4)byteArrayOf(b[2],b[3],b[0],b[1])else b;"badc"->if(b.size==4)byteArrayOf(b[1],b[0],b[3],b[2])else b;else->error("不支持的字节序")}; private fun ByteArray.withCrc()=this+crc(this).let{byteArrayOf(it.toByte(),(it ushr 8).toByte())}; internal fun crc(b:ByteArray):Int{var r=0xffff;for(x in b){r=r xor x.u();repeat(8){r=if(r and 1!=0)(r ushr 1)xor 0xa001 else r ushr 1}};return r};private fun verify(b:ByteArray){require(b.size>=4&&crc(b.copyOfRange(0,b.size-2))==b[b.size-2].u()or(b[b.size-1].u()shl 8)){"RTU CRC 校验失败"}}; private fun readFully(i:java.io.InputStream,b:ByteArray){var n=0;while(n<b.size){val x=i.read(b,n,b.size-n);if(x<0)throw IOException("RTU 响应提前结束");n+=x}}
