package ai.moying.iview.plan

import java.time.*
import java.time.temporal.ChronoUnit

data class Shift(val id: Long, val name: String, val startMinute: Int, val endMinute: Int, val weekdays: Set<DayOfWeek>, val zoneId: String, val enabled: Boolean, val version: Long)
data class ShiftCommand(val name: String, val startMinute: Int, val endMinute: Int, val weekdays: Set<DayOfWeek>, val zoneId: String = "Asia/Shanghai", val enabled: Boolean = true)
data class PlannedDowntime(val id: Long, val deviceId: Long?, val start: Instant, val end: Instant, val reason: String, val version: Long)
data class PlannedDowntimeCommand(val deviceId: Long?, val start: Instant, val end: Instant, val reason: String)
interface ProductionPlanRepository { fun shifts():List<Shift>;fun shift(id:Long):Shift?;fun createShift(c:ShiftCommand):Shift;fun updateShift(id:Long,c:ShiftCommand):Shift?;fun deleteShift(id:Long):Boolean;fun downtime(deviceId:Long,start:Instant,end:Instant):List<PlannedDowntime>;fun createDowntime(c:PlannedDowntimeCommand):PlannedDowntime;fun deleteDowntime(id:Long):Boolean }
open class ProductionPlanException(message:String):RuntimeException(message); class ProductionPlanNotFoundException(message:String):ProductionPlanException(message);class ProductionPlanValidationException(message:String):ProductionPlanException(message)
class ProductionPlanService(private val repository:ProductionPlanRepository) {
 fun shifts()=repository.shifts();fun createShift(c:ShiftCommand):Shift{validate(c);return repository.createShift(c)};fun updateShift(id:Long,c:ShiftCommand):Shift{validate(c);return repository.updateShift(id,c)?:throw ProductionPlanNotFoundException("班次不存在: $id")};fun deleteShift(id:Long){if(!repository.deleteShift(id))throw ProductionPlanNotFoundException("班次不存在: $id")}
 fun downtime(deviceId:Long,start:Instant,end:Instant)=repository.downtime(deviceId,start,end)
 fun createDowntime(c:PlannedDowntimeCommand):PlannedDowntime{if(!c.end.isAfter(c.start)||c.reason.isBlank())throw ProductionPlanValidationException("计划停机时间或原因不正确");return repository.createDowntime(c.copy(reason=c.reason.trim()))};fun deleteDowntime(id:Long){if(!repository.deleteDowntime(id))throw ProductionPlanNotFoundException("计划停机不存在: $id")}
 fun plannedDuration(deviceId:Long,start:Instant,end:Instant):Duration { if(!end.isAfter(start))throw ProductionPlanValidationException("结束时间必须晚于开始时间");val window=Range(start,end);val shiftRanges=repository.shifts().filter{it.enabled}.flatMap{ranges(it,window)};val covered=merge(shiftRanges);val down=repository.downtime(deviceId,start,end).map{Range(it.start,it.end)};return covered.fold(Duration.ZERO){ total,r->total.plus(Duration.between(r.start,r.end).minus(intersectionDuration(r,down))) }.coerceAtLeast(Duration.ZERO) }
 private fun validate(c:ShiftCommand){if(c.name.isBlank()||c.startMinute !in 0..1439||c.endMinute !in 0..1439||c.weekdays.isEmpty())throw ProductionPlanValidationException("班次配置不正确");runCatching{ZoneId.of(c.zoneId)}.getOrElse{throw ProductionPlanValidationException("时区不正确")}}
 private fun ranges(s:Shift,w:Range):List<Range>{val zone=ZoneId.of(s.zoneId);val first=w.start.atZone(zone).toLocalDate().minusDays(1);val last=w.end.atZone(zone).toLocalDate();return generateSequence(first){it.plusDays(1)}.takeWhile{!it.isAfter(last)}.filter{it.dayOfWeek in s.weekdays}.mapNotNull{d->val a=d.atStartOfDay(zone).plusMinutes(s.startMinute.toLong()).toInstant();val b=(if(s.endMinute>s.startMinute)d else d.plusDays(1)).atStartOfDay(zone).plusMinutes(s.endMinute.toLong()).toInstant();Range(maxOf(a,w.start),minOf(b,w.end)).takeIf{it.end.isAfter(it.start)}}.toList()}
 private fun merge(items:List<Range>):List<Range>{val out=mutableListOf<Range>();items.sortedBy{it.start}.forEach{r->val last=out.lastOrNull();if(last==null||r.start.isAfter(last.end))out+=r else out[out.lastIndex]=Range(last.start,maxOf(last.end,r.end))};return out};private fun intersectionDuration(base:Range,items:List<Range>)=merge(items.mapNotNull{Range(maxOf(base.start,it.start),minOf(base.end,it.end)).takeIf{x->x.end.isAfter(x.start)}}).fold(Duration.ZERO){a,r->a.plus(Duration.between(r.start,r.end))};private data class Range(val start:Instant,val end:Instant)
}
