spring:
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/iview}
    username: ${JDBC_USERNAME:iview}
    password: ${JDBC_PASSWORD}
  flyway:
    enabled: true

iview:
  data-source:
    secret: ${IVIEW_DATASOURCE_SECRET}
  auth:
    token-secret: ${IVIEW_AUTH_TOKEN_SECRET}
    bootstrap-admin-password: ${IVIEW_BOOTSTRAP_ADMIN_PASSWORD}
