package ai.moying.iview.production
import ai.moying.iview.common.ApiResponse
import org.springframework.http.HttpStatus
import org.springframework.web.bind.annotation.*
import java.time.Instant
class ProductionRuleRequest { var templateId:Long?=null;var quantityPointId:Long?=null;var qualifiedPointId:Long?=null;var enabled:Int?=null }
@RestController @RequestMapping("/api/v1/production-rules") class ProductionRuleController(private val service:ProductionService){
 @GetMapping fun list()=ApiResponse.success(service.listRules());@PostMapping @ResponseStatus(HttpStatus.CREATED) fun create(@RequestBody b:ProductionRuleRequest)=ApiResponse.success(service.createRule(b.command()));@PutMapping("/{id}") fun update(@PathVariable id:Long,@RequestBody b:ProductionRuleRequest)=ApiResponse.success(service.updateRule(id,b.command(service.getRule(id))));@DeleteMapping("/{id}") fun delete(@PathVariable id:Long):ApiResponse<Nothing>{service.deleteRule(id);return ApiResponse.success()};@PostMapping("/{id}/enable")fun enable(@PathVariable id:Long)=ApiResponse.success(service.setEnabled(id,true));@PostMapping("/{id}/disable")fun disable(@PathVariable id:Long)=ApiResponse.success(service.setEnabled(id,false));private fun ProductionRuleRequest.command(old:ProductionRule?=null)=ProductionRuleCommand(templateId?:old?.templateId?:0,quantityPointId?:old?.quantityPointId?:0,qualifiedPointId?:old?.qualifiedPointId,enabled?.let{it==1}?:old?.enabled?:true)}
@RestController @RequestMapping("/api/v1/production-records") class ProductionRecordController(private val service:ProductionService){@GetMapping fun list(@RequestParam(defaultValue="1")page:Int,@RequestParam(name="page_size",defaultValue="20")size:Int,@RequestParam(name="device_id",required=false)deviceId:Long?)=ApiResponse.success(service.listRecords(ProductionFilter(page,size,deviceId)));@DeleteMapping("/cleanup")fun cleanup(@RequestParam before:Instant)=ApiResponse.success(mapOf("deleted" to service.cleanup(before)))}
