package ai.moying.iview.plan.jdbc
import ai.moying.iview.plan.*
import org.springframework.jdbc.core.RowMapper
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate
import org.springframework.jdbc.core.simple.SimpleJdbcInsert
import org.springframework.stereotype.Repository
import java.time.*
@Repository class JdbcProductionPlanRepository(private val jdbc:NamedParameterJdbcTemplate):ProductionPlanRepository{
 private val si by lazy{ins("iview_shift","shift_name","start_minute","end_minute","weekdays","zone_id","enabled","rule_version")};private val di by lazy{ins("iview_planned_downtime","device_id","start_at","end_at","reason","rule_version")}
 override fun shifts()=jdbc.query("SELECT * FROM iview_shift ORDER BY id",emptyMap<String,Any>(),sm);override fun shift(id:Long)=one("SELECT * FROM iview_shift WHERE id=:id",mapOf("id" to id),sm);override fun createShift(c:ShiftCommand):Shift{val id=si.executeAndReturnKey(v(c,1)).toLong();return requireNotNull(shift(id))};override fun updateShift(id:Long,c:ShiftCommand):Shift?{val n=jdbc.update("UPDATE iview_shift SET shift_name=:shift_name,start_minute=:start_minute,end_minute=:end_minute,weekdays=:weekdays,zone_id=:zone_id,enabled=:enabled,rule_version=rule_version+1 WHERE id=:id",v(c,0)+("id" to id));return if(n==0)null else shift(id)};override fun deleteShift(id:Long)=jdbc.update("DELETE FROM iview_shift WHERE id=:id",mapOf("id" to id))>0
 override fun downtime(deviceId:Long,start:Instant,end:Instant)=jdbc.query("SELECT * FROM iview_planned_downtime WHERE (device_id IS NULL OR device_id=:d) AND start_at<:e AND end_at>:s",mapOf("d" to deviceId,"s" to start,"e" to end),dm);override fun createDowntime(c:PlannedDowntimeCommand):PlannedDowntime{val id=di.executeAndReturnKey(mapOf("device_id" to c.deviceId,"start_at" to c.start,"end_at" to c.end,"reason" to c.reason,"rule_version" to 1)).toLong();return requireNotNull(one("SELECT * FROM iview_planned_downtime WHERE id=:id",mapOf("id" to id),dm))};override fun deleteDowntime(id:Long)=jdbc.update("DELETE FROM iview_planned_downtime WHERE id=:id",mapOf("id" to id))>0
 private fun v(c:ShiftCommand,n:Int)=mapOf("shift_name" to c.name.trim(),"start_minute" to c.startMinute,"end_minute" to c.endMinute,"weekdays" to c.weekdays.joinToString(","){it.value.toString()},"zone_id" to c.zoneId,"enabled" to c.enabled,"rule_version" to n);private fun ins(t:String,vararg c:String)=SimpleJdbcInsert(jdbc.jdbcTemplate).withTableName(t).usingGeneratedKeyColumns("id").usingColumns(*c);private fun <T>one(s:String,p:Map<String,Any?>,m:RowMapper<T>)=jdbc.query(s,p,m).firstOrNull();private fun ti(r:java.sql.ResultSet,n:String)=r.getTimestamp(n).toInstant()
 private val sm=RowMapper{r,_ ->Shift(r.getLong("id"),r.getString("shift_name"),r.getInt("start_minute"),r.getInt("end_minute"),r.getString("weekdays").split(',').filter{it.isNotBlank()}.map{DayOfWeek.of(it.toInt())}.toSet(),r.getString("zone_id"),r.getBoolean("enabled"),r.getLong("rule_version"))};private val dm=RowMapper{r,_ ->PlannedDowntime(r.getLong("id"),(r.getObject("device_id")as?Number)?.toLong(),ti(r,"start_at"),ti(r,"end_at"),r.getString("reason"),r.getLong("rule_version"))}
}
